#!/usr/bin/env bash
# A script to install and configure Nginx on web01 server

sudo apt-get update
sudo apt-get -y install ngin
ufw allow 'Nginx HTTP'x
echo "Hello World!" >  /var/www/html/index.html
sudo service nginx restart
