#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
#+ In a list format
# Where only the part of the name after the first dash is displayed

files=$(find -- * -maxdepth 1| cut -d'-' -f2- )

for f in $files
do
	echo "$f"
done
